"""
Chapter 16: Real-World Agent Patterns, Case Studies from the Field
Hands-On: Case 7 Made Real, Catching Overreach Before It Reaches a User

Extracted from: chapter_16_case_studies.md
Source book: Agentic AI: Building AI Agents and Retrieval Systems,
a Masterclass in LLM Agents, RAG, and Production Deployment.

Every block below was verified by direct execution before being
written into the handbook; run this file top to bottom, or copy
out the section you need. Where a step needs an API key
(OPENAI_API_KEY / ANTHROPIC_API_KEY), it is loaded from a local
.env file via python-dotenv, following Chapter 5's own security
discipline, never hardcoded.
"""


# ---- == Hands-On: Case 7 Made Real, Catching Overreach Before It Reaches a User == ----
DISCLAIMER = ("This is general guidance generated by an AI assistant, not regulated "
              "financial advice. Consult a licensed financial adviser before making "
              "investment decisions.")

def contains_overreach_language(plan_text: str) -> list:
    overreach_phrases = ["guaranteed return", "you should invest", "this is financial advice",
                         "i recommend you buy", "certain to grow"]
    lowered = plan_text.lower()
    return [p for p in overreach_phrases if p in lowered]

def wrap_with_scope_disclaimer(plan_text: str) -> str:
    return f"{plan_text}\n\n---\n{DISCLAIMER}"

draft_plan = "Based on your goals, you should invest 20% of your income into index funds for guaranteed return."
print("overreach phrases found:", contains_overreach_language(draft_plan))

safe_plan = "Based on your stated goals, one option some people consider is allocating a portion of income to diversified index funds."
print("overreach phrases found:", contains_overreach_language(safe_plan))
print(wrap_with_scope_disclaimer(safe_plan))
